### ISSUE TITLE
list for Todos

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/Capstone-project#2]
## Value proposition

**As a user,
**I want to create a list of todos.
**so that i don´t have to remember them.

## Description

<img width="596" alt="list for todos" src="https://user-images.githubusercontent.com/104771076/175937799-892be3f0-4aad-4440-8127-efb81a13ae19.png">

## Acceptance criteria

- [ ] Items are added to the end
- [ ] The form is always at the bottom
- [ ] Todos scroll above the form
- [ ]  Maxlength is 50 chars
- [ ] Whitespace is trimmed
- [ ]  Empty todos are not added
- [ ]  in the form the task input is required  but the due date is optional

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] implement Storybook for TodoForm
- [ ] Implement TodoForm component
- [ ] Write specs for TodoForm
- [ ] Styles component 
- [ ] add TodoForm to App
- [ ]  Render todos in an unordered list
