### ISSUE TITLE
Todo status

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/Capstone-project#3]
## Value proposition

**As auser,
**I want to click the status button to change the color
**so that have a better overview

## Description

<img width="402" alt="update status" src="https://user-images.githubusercontent.com/104771076/175936553-a8ee1bd0-4db2-475a-899a-23d116e665c0.png">

## Acceptance criteria

- [ ] now Todos are unchecked
- [ ] Tap the red "Aufgabe" button and the color will change to yellow and the text will change to "In Arbeit. When you're done, you can tap the yellow button and its color change to green and the text to "Erledigt".
- [ ]  Checking/unchecking does not change sort order

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Setup stories for Todoitem
- [ ] implement status button
- [ ]  Write specs for TodoItem
- [ ] Implement Todoitem 
- [ ] Update state logic in App with Todoitem

**Comment by JessicaLoers** [comment]
**Hi @Mitrovic-Milan** ✌️
well done, so far.  I have some comments. 

**Value proposition**
What's the users benefit of this feature - be more specific.
**For example:**  
**As a** user:  _typo, missing whitespace_
**I want to** change the status of my todos
**So that I**  get a better overview which todos still needs to be done

**Acceptance criteria**
 - now Todos are unchecked **_typo: new todos_** - Tap the red "Aufgabe" button and the color will change to yellow and the text will change to "In Arbeit. When you're done, you can tap the yellow button and its color change to green and the text to "Erledigt" : _From a user and UX/UI perspective, it is unfavorable. To change the status from "In Arbeit" back to "Aufgaben", you will first marking the todo as "Erledigt". In further User Stories you can think about an other solution_
-  Checking/unchecking does not change sort order: _**what means Checking/unchecking?**_ 
_**Notice:**_ It would be a cool feature to sort your todos by priority or status, wouldn't it?  ☝️

- Your formatting is not correct in the "Value proposition".  In markdown you can add bold text with `**I am bold**`

**If you have any question, feel free to as me 🙂**
