### ISSUE TITLE
Delete Button

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/Capstone-project#4]
## Value proposition

**As a** user,
**I want to create a delete button
**so that I can delete finished todos

## Description

<img width="593" alt="Delete Button " src="https://user-images.githubusercontent.com/104771076/175940734-be634ff9-81ec-44bb-a24e-379fa397873c.png">

## Acceptance criteria

- [ ] Highlight a todo and press the delete key

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Write specs for delete
- [ ] Implement delete button
