### ISSUE TITLE
local storige 

### ISSUE THREAD

**Issue by Mitrovic-Milan** [Mitrovic-Milan/Capstone-project#5]
## Value proposition

**As a** user,
**I want to have my todos seved in the browser
**so that I don´t loose my progress in betwenn reloads

## Description

<img src=xxx.png width=320px>

## Acceptance criteria

- [ ] All todos with their done state are persisted
- [ ] Savein takes place immediately for each change 

## Complexity

Small 

## Tasks

- [ ] Create branch
- [ ] Add hook for local Storage
- [ ] Test with empty localStorage

**Comment by p-enz** [comment]
looks good to me. Happy Hacking :)
